name: flutter_folders_structure
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Contains code to deal with internationalized/localized messages, date and number
  # formatting and parsing, bi-directional text, and other internationalisation issues.
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  # A wrap around InheritedWidget to make them easier to use and more reusable.
  provider: ^6.1.2

  # Simple direct service locator that allows to decouple the interface from a concrete
  # implementation and to access the concrete implementation from everyWhere in your App.
  get_it: ^7.6.7


  shared_preferences: ^2.2.3
  package_info_plus: ^5.0.1
  connectivity_plus: ^6.0.3
  device_info_plus: ^9.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.6

# The following section is specific to Flutter packages.
flutter:

  generate: true
  uses-material-design: true

