name: flutter_folders_structure
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter


  # Utulities packages 
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  http: ^1.2.0
  logger: ^2.4.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3

  # State management 
  provider: ^6.1.2
  get_it: ^7.6.7
  get: ^4.6.6
  flutter_bloc: ^8.1.6
  get_storage: ^2.1.1


  # Icons 
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8


  # product specification
  carousel_slider: ^5.0.0

  # Oders
  shared_preferences: ^2.2.3
  package_info_plus: ^5.0.1
  connectivity_plus: ^6.0.3
  device_info_plus: ^9.1.2
  font_awesome_flutter: ^10.7.0
  geolocator: ^11.1.0
  keyboard_actions: ^4.2.0
  android_id: ^0.4.0
  calendar_view: ^1.2.0
  multi_select_flutter: ^4.1.3
  flutter_svg: ^2.0.10+1
  dartz: ^0.10.1
  

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  # Code generator for data classes, unions, and cloning.
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  


#--------------- ./ PACKAGES END ------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

# The following section is specific to Flutter packages.
flutter:

  generate: true
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/fonts/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/images/animations/
    - assets/images/app_logos/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/images/products/
    - assets/images/products/
    - assets/images/app_logos/
    - assets/logos/
    - assets/vectors/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800
        
        

